In [ ]:
import torch 
import torch.nn as nn
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [23]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = torch.linspace(-5, 5, 10, device=device,dtype=torch.float32)
y = torch.linspace(-5, 5, 10, device=device,dtype=torch.float32)
grid_x, grid_y = torch.meshgrid(x, y, indexing='xy')
z = torch.tensor(100, device=device, dtype=torch.float32)
wb = torch.tensor([2,3], device=device, dtype=torch.float32)
total_potential = z+ wb[0] * grid_x + wb[1] * grid_y
print(total_potential[:3, :3])

tensor([[75.0000, 77.2222, 79.4444],
        [78.3333, 80.5556, 82.7778],
        [81.6667, 83.8889, 86.1111]], device='cuda:0')


In [11]:
x_coords = torch.linspace(-5, 5, 10, device=device,dtype=torch.float32)
y_coords = torch.linspace(-5, 5, 10, device=device,dtype=torch.float32)
print(f"\nx_coords 张量: {x_coords}")
print(f"y_coords 张量: {y_coords}")
print(f"x_coords 的形状: {x_coords.shape}")
print(f"y_coords 的形状: {y_coords.shape}")
print(f"x_coords 的设备: {x_coords.device}")
print(f"y_coords 的设备: {y_coords.device}")



x_coords 张量: tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000], device='cuda:0')
y_coords 张量: tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000], device='cuda:0')
x_coords 的形状: torch.Size([10])
y_coords 的形状: torch.Size([10])
x_coords 的设备: cuda:0
y_coords 的设备: cuda:0


In [15]:
grid_x, grid_y = torch.meshgrid(x_coords, y_coords, indexing='xy')

print(f"\ngrid_x 的形状: {grid_x.shape}")
print(f"grid_y 的形状: {grid_y.shape}")
print(f"grid_x 的设备: {grid_x.device}")
print(f"grid_y 的设备: {grid_y.device}")
print(f"grid_x (前3行3列):\n{grid_x[:3, :3]}")
print(f"grid_y (前3行3列):\n{grid_y[:3, :3]}")


grid_x 的形状: torch.Size([10, 10])
grid_y 的形状: torch.Size([10, 10])
grid_x 的设备: cuda:0
grid_y 的设备: cuda:0
grid_x (前3行3列):
tensor([[-5.0000, -3.8889, -2.7778],
        [-5.0000, -3.8889, -2.7778],
        [-5.0000, -3.8889, -2.7778]], device='cuda:0')
grid_y (前3行3列):
tensor([[-5.0000, -5.0000, -5.0000],
        [-3.8889, -3.8889, -3.8889],
        [-2.7778, -2.7778, -2.7778]], device='cuda:0')


In [16]:
# --- 4. 创建物理参数 ---
# 创建一个代表“全局基础势能”的标量（0维张量），base_potential = torch.tensor(100.0)。
base_potential = torch.tensor(100.0, device=device)
# 创建一个代表“坐标影响因子”的张量，coord_factor = torch.tensor([2.0, -3.0])，分别对应x和y方向。
coord_factor = torch.tensor([2.0,-3.0], device=device)

print(f"\nbase_potential 张量: {base_potential}")
print(f"coord_factor 张量: {coord_factor}")
print(f"base_potential 的形状: {base_potential.shape}")
print(f"coord_factor 的形状: {coord_factor.shape}")
print(f"base_potential 的设备: {base_potential.device}")
print(f"coord_factor 的设备: {coord_factor.device}")


base_potential 张量: 100.0
coord_factor 张量: tensor([ 2., -3.], device='cuda:0')
base_potential 的形状: torch.Size([])
coord_factor 的形状: torch.Size([2])
base_potential 的设备: cuda:0
coord_factor 的设备: cuda:0


In [18]:
# --- 5. 利用广播机制计算总势能 ---
# 现在，我们要计算每个点的总势能，公式为：
total_potential = base_potential + coord_factor[0] * grid_x + coord_factor[1] * grid_y
print("\n总势能已计算完成。")

print(f"\nTotal_Potential 的形状: {total_potential.shape}")
print("Total_Potential 的前3行3列:")
print(total_potential[:3, :3])

print("\n--- 任务完成 ---")


总势能已计算完成。

Total_Potential 的形状: torch.Size([10, 10])
Total_Potential 的前3行3列:
tensor([[105.0000, 107.2222, 109.4444],
        [101.6667, 103.8889, 106.1111],
        [ 98.3333, 100.5556, 102.7778]], device='cuda:0')

--- 任务完成 ---
